### ISSUE TITLE
有计划win版吗

### ISSUE THREAD

**Issue by huawuhen** [caol64/wenyan#1]
有计划win版吗

**Comment by caol64** [comment]
是的，这个需求已经被多次提出，很快就会进行开发。

**Comment by coracoo** [comment]
借楼问，有机会用docker部署么

**Comment by caol64** [comment]
> 借楼问，有机会用docker部署么

这是个MAC下的原生应用，使用docker部署意义不大吧？

**Comment by caol64** [comment]
> 对于自媒体来说确实是个好工具，如果有window发布计划，能否适配docker实现web使用～

你的意思是否是：再出个web版，并推出该版本的docker镜像？

**Comment by coracoo** [comment]
> > 对于自媒体来说确实是个好工具，如果有window发布计划，能否适配docker实现web使用～
> 
> 
> 
> 你的意思是否是：再出个web版，并推出该版本的docker镜像？

是的，大佬就是这个意思

**Comment by caol64** [comment]
> > > 对于自媒体来说确实是个好工具，如果有window发布计划，能否适配docker实现web使用～
> > 
> > 
> > 你的意思是否是：再出个web版，并推出该版本的docker镜像？
> 
> 是的，大佬就是这个意思

了解，此版本优先级较低，推出win版之后再考虑。

你可以先使用在线版本：

https://doocs.github.io/md/
https://markdown.com.cn/editor/

**Comment by pengqg4786** [comment]
> 对于自媒体来说确实是个好工具，如果有window发布计划，能否适配docker实现web使用～
看看这个，有可能能满足你的docker部署的需求
https://github.com/doocs/md

**Comment by coracoo** [comment]
感谢大佬们指路
