### ISSUE TITLE
因为我贴了个超大 svg 进去，左侧编辑栏被卡白屏，右侧展示区正常。

### ISSUE THREAD

**Issue by c-lins** [caol64/wenyan#15]
鬼故事，因为我贴了个超大 svg 进去，左侧编辑栏被卡白屏，右侧展示区正常。

卸载重载也无法解决，每次重装后打开右侧都能正常展示，但左侧空白，无光标选 中，内存飙升，应用卡死。

**Comment by caol64** [comment]
这是因为左侧编辑器里的内容缓存了，你可以打开finder，shift+cmd+G打开对话框，进入到~/Library/Containers/com.yztech.WenYan目录，将里面的内容删除，再重新打开文颜应用。

顺便一说，你能把这个svg分享一下吗？我看能不能优化。
