### ISSUE TITLE
复制到微信公众号格式不对

### ISSUE THREAD

**Issue by hxzhouh** [caol64/wenyan#23]
version : 版本2.3
我录了一个视频，如图

https://github.com/user-attachments/assets/eaaed6f5-4299-494c-bfce-d8c0d4a13f23

**Comment by caol64** [comment]
是什么主题？自定义主题的话把css贴一下。

**Comment by hxzhouh** [comment]
默认主题，公众号自带的几个主题都试了，都不行。

**Comment by caol64** [comment]
貌似公众号编辑器悄悄改了东西，紧急发布一个版本适配。v2.3.1

**Comment by hxzhouh** [comment]
感谢，已经可以了。
