### ISSUE TITLE
新版本WIN平台什么时候可以发布，期待中~

### ISSUE THREAD

**Issue by null119** [caol64/wenyan#4]

**Comment by caol64** [comment]
看看能不能国庆前赶出来，但大概率要国庆后了。

**Comment by caol64** [comment]
新版本windows已经发布。

[https://yuzhi.tech/docs/wenyan/windows](https://yuzhi.tech/docs/wenyan/windows)

**Comment by null119** [comment]
> 新版本windows已经发布。
> 
> https://yuzhi.tech/docs/wenyan/windows

大佬辛苦，已下载使用，非常棒，再次感谢！！！
