### ISSUE TITLE
希望能支持自定义CSS

### ISSUE THREAD

**Issue by sumruler** [caol64/wenyan#6]

**Comment by caol64** [comment]
👌

**Comment by caol64** [comment]
已支持

**Comment by sumruler** [comment]
> 已支持

感谢，这样就完美了，我fork了一下，后面pr一个我自制的主题。

**Comment by sumruler** [comment]
> 已支持

刚刚看了一下好像windows版还不是2.0，可以更新一下win的版本吗

**Comment by caol64** [comment]
由于精力问题，win版可能要稍迟一点。关于win版的意见和建议，可以移步[https://github.com/caol64/wenyan/discussions/12](https://github.com/caol64/wenyan/discussions/12)讨论。

**Comment by caol64** [comment]
> > 已支持
> 
> 刚刚看了一下好像windows版还不是2.0，可以更新一下win的版本吗

windows 2.0版已发布。

**Comment by sumruler** [comment]
> > > 已支持
> > 
> > 
> > 刚刚看了一下好像windows版还不是2.0，可以更新一下win的版本吗
> 
> windows 2.0版已发布。

网站上的下载链接还是1.1.1版本，2.0版本应该在哪里下载呢？

**Comment by caol64** [comment]
> > > > 已支持
> > > 
> > > 
> > > 刚刚看了一下好像windows版还不是2.0，可以更新一下win的版本吗
> > 
> > 
> > windows 2.0版已发布。
> 
> 网站上的下载链接还是1.1.1版本，2.0版本应该在哪里下载呢？

不好意思，下载链接现在正常了。
