### ISSUE TITLE
能否支持一下macOS Monterey

### ISSUE THREAD

**Issue by windowshome** [caol64/wenyan#7]
您好，能否支持一下低版本的macOS系统，我的mac 只能支持到 macOS Monterey 12 版本，但是特别想使用这个软件；

**Comment by caol64** [comment]
👌

**Comment by windowshome** [comment]
大佬，大概什么时候能抽空支持一下这个呢

**Comment by caol64** [comment]
已经完成一个版本，因为我没有macOS Monterey 系统，需要你测试下功能。

[下载](https://github.com/caol64/wenyan/releases/download/1.8beta/default.dmg)

**Comment by windowshome** [comment]
大佬，版本不好使，类似于打包的一个32位的包一样的提示；
<img width="674" alt="image" src="https://github.com/user-attachments/assets/d2d3b7b3-936b-4754-9123-2a17573489f3">

**Comment by caol64** [comment]
抱歉，我还不会打可分发的dmg包。等着appstore下载吧。

**Comment by caol64** [comment]
已可以从appstore下载
